delimDict = {
    'Integer' : ['space'],
    'Decimal' : ['space'],
    'String' : ['space'],
    'Boolean' : ['space'],
    'Struct' : ['space'],
    'Generate' : ['space'],
    'Absorb' : ['space'],
    'Discharge' : ['space'],
    'Switch' : ['space'],
    'For' : ['space'],
    'In' : ['space'],
    'Sys' : ['space'],
    'Sys.Call' : ['space'],
    'Execute' : ['space'],
    'Fixed' : ['space'],
    'Return' : ['space'],
    'Default' : [':'],
    'Else' : [':'],
    'If' : ['space', '('],
    'Elif' : ['space', '('],
    'And' : ['space', '('],
    'Or' : ['space', '('],
    'Not' : ['space', '('],
    'While' : ['space', '('],
    'End.Switch' : ['newline'],
    'Break' : ['newline'],
    'Continue' : ['newline'],
    'Avoid' : ['newline'],
    'Link_Start' : ['newline'],
    'Link_End' : ['newline', ''],
    'lit_decposi' : ['space', 'newline', '>=', '<=', '!=', 
                     '>', '<', '==', ':', ',', 
                     '+', '-', '//', '**', '*', '/', 
                     '%', ')', ']', '}'],
    'lit_decnega' : ['space', 'newline', '>=', '<=', '!=', 
                     '>', '<', '==', ':', ',', 
                     '+', '-', '//', '**', '*', '/', 
                     '%', ')', ']', '}'],
    'lit_intposi' : ['space', 'newline', '>=', '<=', '!=', 
                     '>', '<', '==', ':', ',', 
                     '+', '-', '//', '**', '*', '/', 
                     '%', ')', ']', '}', ':'],
    'lit_intnega' : ['space', 'newline', '>=', '<=', '!=', 
                     '>', '<', '==', ':', ',', 
                     '+', '-', '//', '**', '*', '/', 
                     '%', ')', ']', '}', ':'],
    'lit_str' : ['id', 'reserved_word', ',', '(', ')', '[', ']', '{', '}', ':'], 
    'lit_bool' : ['id', 'reserved_word', ',', '(', ')', '[', ']', '{', '}'],
    'less_than_equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'great_than_equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'not_equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'less_than' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'greater_than' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'equal_equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-', 'lit_str'],
    'minus_equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-', 'lit_str'],
    'plus_equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-', 'lit_str'],
    'times_equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-', 'lit_str'],
    'divide_equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-', 'lit_str'],
    'times_times_equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-', 'lit_str'],
    'modulo_equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-', 'lit_str'],
    'divide_divide_equal' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-', 'lit_str'],
    'plus' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'minus' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'times' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'divide' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'times_times' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'divide_divide' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'modulo' : ['space', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', '(', '-'],
    'open_par' : ['lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', 'And', 'Or', 'Not', '(', ')'],
    'close_par' : ['space', '[', '+', '-', '*', '/', '%', '**', '//', '>', '<', '==', '!=', '>=', '<=', 'And', 'Or', 'Not', ':', ')'],
    'open_brace' : ['id', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega', 'lit_str', '}'],
    'close_brace' : ['id', 'reserved_word', ')', '+', '-', '//', '**', '*', '/', '%', '=', '-=', '+=', '*=', '/=', '**=', '%=', '//=', '<=', '>=', '!=', '>', '<', '==', 'And', 'Or', 'Not'],
    'open_bracket' : ['id', 'reserved_word', 'id', '\"', '\“', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega'],
    'close_bracket' : ['space', 'newline', ''],
    'comma' : ['space', 'id', 'id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega'],
    'colon' : ['id', 'reserved_word', '['], 
    'period' : ['id', 'lit_decposi', 'lit_decnega', 'lit_intposi', 'lit_intnega'],
    'id' : ['space', 'newline', '.', ',', '(', ')', '[', ']', 
            '+', '-', '//', '**', '*', '/', '%', '=', 
            '-=', '+=', '*=', '/=', '**=', 
            '%=', '//=', '>=', '<=', '!=', 
            '>', '<', '==', ':', '{']
}